# 07/01/2026

## Quick Sort:
--quick sort is a sorting algorithm used to arrange elements (like numbers) in ascending or descending order.

--Work using Divide and conquer approach


--__Divide:__ split problem into smaller parts.

--__conquer:__ solve each smaller part.

--__combine:__ put the solution toghter to get the final answer.




In [1]:
def quick_sort(numbers):
    if len(numbers) <= 1:
        return numbers
    #Pivot element
    pivot = numbers[len(numbers) // 2]
    left = [x for x in numbers if x < pivot]
    middle = [x for x in numbers if x == pivot]
    right = [x for x in numbers if x > pivot]

    return quick_sort(left) + middle + quick_sort(right)
    


numbers = [56,43,23,90,12,21,55]
sorted_list = quick_sort(numbers)
print(sorted_list)




[12, 21, 23, 43, 55, 56, 90]


In [24]:
# to sort the list of strings using quick sort and ensure the sort in case  sensitive
def quick_sort1(str1):
    if len(str1) <= 1:
        return str1
    #Pivot element
    pivot = str1[len(str1) // 2]
    #return pivot
    left = [s for s in str1 if s.lower() < pivot.lower()]
    middle = [s for s in str1 if s.lower() == pivot.lower()]
    right = [s for s in str1 if s.lower() > pivot.lower()]

    return quick_sort1(left) + middle + quick_sort1(right)

str1 = ["mayuri","yashshri","Gauri","Yashika","Sam","Mohan","Yamini","gayu"]
#str1 = ["Gauri","gana","aman","Ishita","Radha"]

sorted_list = quick_sort1(str1)
print(sorted_list)




['Gauri', 'gayu', 'mayuri', 'Mohan', 'Sam', 'Yamini', 'Yashika', 'yashshri']


In [30]:
# to sort the list of strings using quick sort and ensure the sort in case  sensitive
def quick_sort1(str1):
    if len(str1) <= 1:
        return str1
    #Pivot element
    pivot = str1[len(str1) // 2]
    #return pivot
    left = [s for s in str1 if s.upper() < pivot.upper()]
    middle = [s for s in str1 if s.upper() == pivot.upper()]
    right = [s for s in str1 if s.upper() > pivot.upper()]

    return quick_sort1(left) + middle + quick_sort1(right)

str1 = ["z","y","Y","Z","A","c","p","R","w"]

sorted_list = quick_sort1(str1)
print(sorted_list)




['A', 'c', 'p', 'R', 'w', 'y', 'Y', 'z', 'Z']


# Linear Search
--Linear search is sequential search algorithm where we start from one end and check every element of the list until the desired element is found .it is simplest searching algorithm

###### Linearsearch(array,key)
###### for each item in array
###### if item ==  value
###### return its index



In [45]:
# Linear Search example 
def sequential_search(nlist,key):
    pos = 0
    found = False

    while pos < len(nlist) and not found:
        if nlist[pos] == key:
            found = True
        else:
            pos += 1 
    return found,pos
print(sequential_search([45,98,23,12,99,34,22], 10))
print(sequential_search(["Mango","Cherry","Strawberries","Grapes","Pineapple","Apple","Guava"], "Grapes"))

(False, 7)
(True, 3)


In [52]:
def search_using_for(n,key):
    for index in range(len(n)):
        if n[index] == key:
            return index
    return False, -1

n = [76,34,23,12,90,76]
result = search_using_for(n,12)
print(result)

3


# Binary Search
--Binary search is a searching algorithm for finding an elements position in sorted array.

--In this approach,the element is always searched in the middle of portion of an array.

Binary search Working in two ways:

1.iterative Method

2.Recursive Method

--The recursive method follow the divide and conquer approch.

In [55]:
def binary_using_itertive(array,target):
    low  = 0
    high = len(array) - 1
    while low <= high:
        mid = (low + high) // 2

        if array[mid] == target:
            return True,mid
        elif array[mid] < target:
            low = mid + 1
        else:
            high = mid - 1
    return False, -1

array = [3,4,5,6,7,8,99]
print(binary_using_itertive(array,6))
print(binary_using_itertive(array,10))

(True, 3)
(False, -1)


In [63]:
def binary_using_itertive(array,target):
    low  = 0
    high = len(array) - 1
    while low <= high:
        mid = (low + high) // 2

        if array[mid] == target:
            return True,mid
        elif array[mid] < target:
            low = mid + 1
        else:
            high = mid - 1
    return False, -1

array = ['a','b','c','d','e','f']
res,index =  binary_using_itertive(array,'d')
print(f"{res} : {index}")


True : 3


In [65]:
# Using Recursive
def binary_using_recursive(arr,target,low,high):
    if low > high:
        return False,-1

    mid = (low + high) // 2
    if arr[mid] == target:
        return True,mid
    elif arr[mid] < target:
        return binary_using_recursive(arr,target,mid + 1,high)
    else:
        return binary_using_recursive(arr,target,low,mid - 1)

arr = [4,5,6,7,8,9,10]
print(binary_using_recursive(arr,8,0,len(arr) - 1))

(True, 4)


# Module



In [1]:
print(help("modules"))


Please wait a moment while I gather a list of all available modules...

test_sqlite3: testing with SQLite version 3.50.4


C:\Users\DELL\AppData\Local\Programs\Python\Python314\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
C:\Users\DELL\AppData\Local\Programs\Python\Python314\Lib\pkgutil.py:76: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  __import__(info.name)
W0107 11:06:32.168000 9376 site-packages\torch\distributed\elastic\multiprocessing\redirects.py:29] NOTE: Redirects are currently not supported in Windows or MacOs.
C:\Users\DELL\AppData\Local\Programs\Python\Python314\Lib\pkgutil.py:76: DeprecationWarning: `torch.distributed._shard.checkpoint` will be deprecated, use `torch.distributed.checkpoint` instead
  __import__(info.name)
C

IPython             _yaml               io                  rfc3339_validator
PIL                 _zoneinfo           ipaddress           rfc3986_validator
__future__          _zstd               ipykernel           rfc3987_syntax
__hello__           abc                 ipykernel_launcher  rlcompleter
__phello__          annotationlib       ipython_pygments_lexers rpds
_abc                antigravity         isoduration         runpy
_aix_support        anyio               isympy              sched
_android_support    argon2              itertools           scipy
_apple_support      argparse            jedi                seaborn
_argon2_cffi_bindings array               jinja2              secrets
_ast                arrow               joblib              select
_ast_unparse        ast                 json                selectors
_asyncio            asttokens           json5               send2trash
_bisect             async_lru           jsonpointer         setuptools
_blake2      

In [6]:
import math
print(dir(math))
print(math.pi)

['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'cbrt', 'ceil', 'comb', 'copysign', 'cos', 'cosh', 'degrees', 'dist', 'e', 'erf', 'erfc', 'exp', 'exp2', 'expm1', 'fabs', 'factorial', 'floor', 'fma', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'isqrt', 'lcm', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'nextafter', 'perm', 'pi', 'pow', 'prod', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'sumprod', 'tan', 'tanh', 'tau', 'trunc', 'ulp']
3.141592653589793


In [7]:
from math import pi,factorial
print(pi)
print(factorial(5))

3.141592653589793
120


In [9]:
import math as m
print(m.pi)
print(m.factorial(6))

3.141592653589793
720


In [13]:
from math import *
print(pi)

3.141592653589793


In [14]:
print(__name__)

__main__


In [15]:
import qwert
print(qwert.name)


1234567


In [1]:
from student import Student
s1 = Student('Gauri', 'Gauri@gmail.com')
s1.display()

name : Gauri
email : Gauri@gmail.com


In [7]:
#create a employee module and display the employee info
# using __init__() and __str__()

In [2]:
import Employee

e1 = Employee.Employee(101, "uma", 342344)
print(e1)   # <-- REQUIRED to trigger __str__()


Name: uma
ID: 101
Salary: 342344


In [7]:
import numpy as np
np.array([1,2,3,4,5])
type(np.array)
np.arange(15).reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [29]:
# 2 dimensional array
import numpy as np
a = np.arange(15).reshape(3,5)
print(a)
print(a.dtype)
print(a.itemsize)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
int64
8


In [34]:
# 3D array
import numpy as np


b = np.arange(24).reshape(2,6,2)


print(b)
print("\n")
print(b[1][0][0])
print("\n")
print(b.ndim)
print("\n")
print(b.shape)
print("\n")
print(b.itemsize)



c = np.array([5,6,7.7])
print("\n")
print(c.dtype)
print("\n")
print(c.itemsize)




[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]
  [18 19]
  [20 21]
  [22 23]]]


12


3


(2, 6, 2)


8


float64


8


In [47]:
# create full of zero array
import numpy as np
z = np.zeros ((3,4))
print(z)

one = np.ones((2,3,4),dtype = np.int32)
print(one)

empty = np.empty((2,3))
print(empty)

d = np.arange(3)
print(np.exp(d))
print(d ** 2 )
print(d < 5)
f = np.arange(3)
print(np.add(f,d))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[[0. 0. 0.]
 [0. 0. 0.]]
[1.         2.71828183 7.3890561 ]
[0 1 4]
[ True  True  True]
[0 2 4]


In [48]:
import pandas as pd
#student mark analysis
#read data from .csv file
df = pd.read_csv("Book1.csv")
print(df)
#calculate the total 
df["Total"] = df["math"] + df["science"] +df["english"]

#calculate the average
df["Average"] = df["Total"] / 3

#print(df)
#pass or fail
df["Result"] = (df[["math", "science", "english"]] >= 40).all(axis = 1)

#print(df)
#find topper
topper = df.loc[df["Total"].idxmax()]
print("Topper: ")
print(topper["name"], "with", topper["Total"], "marks")



     name  math  science  english
0  preeti    34       98       77
1      om    56       56       96
2  yogesh    89       77       88
Topper: 
yogesh with 254 marks


In [49]:
#Making a dice game using pandas
import pandas as pd
import random

#set players
players=["Gopal","Govind"]

#set rounds
rounds=5

df=pd.DataFrame(index=players)

#roll the dice for each round
for r in range(1,rounds+1):
    df[f"Round {r}"]=[random.randint(1,6) for _ in players]

print(df)

#calculate total
df["Total"]=df.sum(axis=1)
print(df)

#Print Winnder
winner=df["Total"].idxmax()
print(f"The Winner is {winner}")



        Round 1  Round 2  Round 3  Round 4  Round 5
Gopal         5        4        3        4        4
Govind        4        3        2        3        4
        Round 1  Round 2  Round 3  Round 4  Round 5  Total
Gopal         5        4        3        4        4     20
Govind        4        3        2        3        4     16
The Winner is Gopal


In [55]:
# data (question)
'''Name    Age 
jaya    23
vinay   25
tina    15
gana    13
era     21
create a data frame using above data 
show the name who are applicable for voting (Age > 18)
except tina display the data frame 
add one column - city in data frame 
display the whose city is not equal to pune
display the only names which started with "G"
print only the top 3 rows
print only last 2 rows
display the data whose city name started with "M"
empname = ["kkjj","jebvjbjkd","yuyu"]
department = ["HR","A/C", "Development"]
using above 2 list create a dataframe'''


import pandas as pd

# Create DataFrame
data = {
    "Name": ["jaya", "vinay", "tina", "gana", "era"],
    "Age": [23, 25, 15, 13, 21]
}
df = pd.DataFrame(data)
print("Original DataFrame:\n", df)

print("\nVoting eligible (Age > 18) except tina:")
print(df[(df["Age"] > 18) & (df["Name"] != "tina")])

df["City"] = ["Pune", "Mumbai", "Delhi", "Nagpur", "Mumbai"]
print("\nAfter adding City column:\n", df)

print("\nCity not equal to Pune:")
print(df[df["City"] != "Pune"])

print("\nNames starting with 'G':")
print(df[df["Name"].str.startswith("g")]["Name"])

print("\nTop 3 rows:")
print(df.head(3))

print("\nLast 2 rows:")
print(df.tail(2))

print("\nCity starting with 'M':")
print(df[df["City"].str.startswith("M")])

empname = ["kkjj", "kdjksjf", "yuyu"]
department = ["HR", "A/C", "Development"]

emp_df = pd.DataFrame({
    "EmpName": empname,
    "Department": department
})
print("\nEmployee DataFrame:")
print(emp_df)



Original DataFrame:
     Name  Age
0   jaya   23
1  vinay   25
2   tina   15
3   gana   13
4    era   21

Voting eligible (Age > 18) except tina:
    Name  Age
0   jaya   23
1  vinay   25
4    era   21

After adding City column:
     Name  Age    City
0   jaya   23    Pune
1  vinay   25  Mumbai
2   tina   15   Delhi
3   gana   13  Nagpur
4    era   21  Mumbai

City not equal to Pune:
    Name  Age    City
1  vinay   25  Mumbai
2   tina   15   Delhi
3   gana   13  Nagpur
4    era   21  Mumbai

Names starting with 'G':
3    gana
Name: Name, dtype: object

Top 3 rows:
    Name  Age    City
0   jaya   23    Pune
1  vinay   25  Mumbai
2   tina   15   Delhi

Last 2 rows:
   Name  Age    City
3  gana   13  Nagpur
4   era   21  Mumbai

City starting with 'M':
    Name  Age    City
1  vinay   25  Mumbai
4    era   21  Mumbai

Employee DataFrame:
   EmpName   Department
0     kkjj           HR
1  kdjksjf          A/C
2     yuyu  Development
